version: "3"
services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
      - prisma
    links:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your_mysql_root_password
      - MYSQL_DATABASE=your_database_name
      - MYSQL_USER=your_mysql_user
      - MYSQL_PASSWORD=your_mysql_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  prisma:
    build:
      context: .
      dockerfile: prisma/Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://your_mysql_user:your_mysql_password@db:3306/your_database_name
    volumes:
      - prisma:/prisma

volumes:
  db_data:
  prisma:
