

        
###
GET http://localhost:5000/ralan/tangani/obat

###
GET http://localhost:5000/ralan/tangani/obat/23062719581121122925

###
GET http://localhost:5000/ralan/tangani/obat/resepke/rt/23062719581121122925

###
GET http://localhost:5000/ralan/tangani/obat/nourut/rr/23062719581121122925/1


###
POST  http://localhost:5000/ralan/tangani/obat
Content-Type: application/json

{
        "no_transaksi": "2306150000013101",
        "no_registrasi": "2306150002",
        "resep": "RR2",
        "no_urut": "2",
        "id_barang": 110032,
        "racikan_jumlah": "racikan_jumlah",
        "racikan_jumlah_diambil": "racikan_jumlah_diambil",
        "racikan_kemasan": "racikan_kemasan",
        "qty": "qty",
        "satuan": "satuan",
        "aturan_pakai": "aturan_pakai",
        "harga_jual": "harga_jual",
        "status_harus_bayar": "status_harus_bayar"
}

###
POST  http://localhost:5000/farmasi/barang/penjualan/2306150002
Content-Type: application/json

{
        "no_transaksi": "2306150000013101",
        "no_registrasi": "2306150002",
        "total_transaksi": "90000"
    
}

# pengecekan nomor urutan resep umum pada pasien ralan
###
GET http://localhost:5000/ralan/tangani/obat/cekurutan/rr/23062713091121122923

###
GET http://localhost:5000/farmasi/barang/penjualan/totaltransaksi/2306150002

###
GET http://localhost:5000/ralan/tangani/obat/general/2306150002  

###
GET http://localhost:5000/pembayaran/totaltagihan/2306150002  

# hapus data
###
DELETE  http://localhost:5000/ralan/tangani/obat/58
