###
POST http://localhost:5000/ralan/pasien/daftar
Content-Type: application/json

{
    "id_pasien_rm": 1118030004,
    "poliklinik": "umum",
    "id_pembayaran": 1,
    "dokter": "rojaur",
    "jenis_pasien": "BPJS",
    "deposit": "50000",
    "jenis_konsultasi": "datang langsung",
    "no_antrian": "A12"

}


###
GET http://localhost:5000/ralan/pasien/all?search=
###

GET http://localhost:5000/jadwal/poli?nama_poli=umum&nama_hari=senin


###
GET http://localhost:5000/ralan/poliklinik/jadwal?

###
GET http://localhost:5000/ralan/poliklinik/jadwal?hari=3

###
GET http://localhost:5000/ralan/pasien/2

###
GET http://localhost:5000/ralan/poliklinik

###
DELETE  http://localhost:5000/ralan/pasien/2

