
###
GET http://localhost:5000/rm/
###
GET http://localhost:5000/igd/pasien/all
###
GET http://localhost:5000/igd/pasien/16

###
GET http://localhost:5000/rm/igd/38


###
GET http://localhost:5000/search?query=1
###
GET http://localhost:5000/igd/pasien?search=r&page=&limit=5

###
GET http://localhost:5000/rm

###
POST http://localhost:5000/rm
Content-Type: application/json

{
               "kitas": "KTP",
                "no_kitas":"12009029102901",
                "nama_lengkap":"Bolb",
                "tempat_lahir":"Aceh",
                "tanggal_lahir":"12-12-2012",
                "kontak_pasien":"081212898021",
                "kelamin":"Laki-laki",
                "golongan_darah":"O+",
                "agama":"Islam",
                "status_kawin":"belum menikah",
                "pendidikan":"S1",
                "pekerjaan":"entrepeuneur",
                "alamat_pasien_provinsi":"Provinsi Aceh",
                "alamat_pasien_kota":"Kabupaten Aceh Besar",
                "alamat_pasien_kec":"Kecamatan Darul Imarah",
                "alamat_pasien_desa":"Kecaamatan Darul Imarah",
                "alamat_pasien_detail":"Kecaamatan Darul Imarah",
                "nama_penanggungjawab":"rosalia",
                "kontak_pj":"0909209120",
                "alamat_pj_provinsi":"alamat_pj_provinsi",
                "alamat_pj_kota":"alamat_pj_kota",
                "alamat_pj_kec":"alamat_pj_kec",
                "alamat_pj_desa":"alamat_pj_desa",
                "alamat_pj_detail":"alamat_pj_detail"

}
###
POST http://localhost:5000/igd/pasien/register
Content-Type: application/json

{
    "id_pasien_rm": 2,
    "tgl_masuk": "12-12-2021",
    "jam_masuk": "12:12",
    "cara_masuk": "datang sendiri",
    "asal_rujukan": "RSUD",
    "alasan_rujukan": "sakit parah",
    "dokter_merujuk": "dr.kem",
    "pembayaran_igd": "BPJS"
}


###
PATCH  http://localhost:5000/igd/pasien/checkout/28
Content-Type: application/json

{

    "status": "status"

}

###
DELETE http://localhost:5000/form/default/ralan/1


# create data tindakan pasien igd by id pasien igd
###
POST http://localhost:5000/igd/pasien/tindakan
Content-Type: application/json

{
    "id_list_tindakan_igd":5 ,
    "id_pasien_igd": 6,
    "jam_tindakan": "12:12",
    "catatan": "telah dilakukan"

}

# create list tindakan yang ada di igd
###
POST http://localhost:5000/igd/tindakan/list
Content-Type: application/json

{
    "tindakan": "cuci hidung"

}

# cek tindakan apa saja yang diberika kepada pasien di igd by id
###
GET http://localhost:5000/igd/pasien/list/penanganan

# hapus data tindakan pasien igd
###
DELETE http://localhost:5000/igd/pasien/tindakan/8

# hapus data list tindakan pasien igd
###
DELETE http://localhost:5000/igd/tindakan/list/5


# tambah pekerjaan ke tabel pekerjaan
###
POST http://localhost:5000/pekerjaan
Content-Type: application/json

{
    "nama_pekerjaan": "TNI/Polri"

}

# tampilkan semua list pekerjaan
###
GET http://localhost:5000/pekerjaan

# tambah pekerjaan ke tabel pekerjaan
###
POST http://localhost:5000/agama
Content-Type: application/json

{
    "list_agama": "Budha"

}

# tampilkan semua list pekerjaan
###
GET http://localhost:5000/agama

# tambah pekerjaan ke tabel pekerjaan
###
POST http://localhost:5000/golongandarah
Content-Type: application/json

{
    "list_golongan_darah": "O+"

}

# tampilkan semua list pekerjaan
###
GET http://localhost:5000/golongandarah

# tambah pekerjaan ke tabel pekerjaan
###
POST http://localhost:5000/pendidikan
Content-Type: application/json

{
    "list_pendidikan": "S3"

}

# tampilkan semua list pekerjaan
###
GET http://localhost:5000/pendidikan

# tambah pekerjaan ke tabel pekerjaan
###
POST http://localhost:5000/statuskawin
Content-Type: application/json

{
    "list_status_kawin": "Cerai"

}

# tampilkan semua list pekerjaan
###
GET http://localhost:5000/statuskawin


# tampilkan semua list pendaftaran igs
###
GET http://localhost:5000/igd/pasien/all


# hapus data pasien terdaftar di igd
###
DELETE http://localhost:5000/igd/pasien/19


# tampilkan triase pasien igd 
###
GET http://localhost:5000/igd/pasien/penanganan/triase/17

# add triase pasien igd 
###
POST http://localhost:5000/igd/pasien/penanganan/triase
Content-Type: application/json

{
    "id_pasien_igd": 17,
    "keluhan_utama": "Darah manis"

}

# update triase pasien igd
###
PATCH  http://localhost:5000/igd/pasien/penanganan/triase/14
Content-Type: application/json

{
    "keluhan_utama": "lapar"

}


# tampilkan triase tanda vital pasien igd 
###
GET http://localhost:5000/igd/pasien/penanganan/triase/tandavital/27

# add triase tanda vital pasien igd 
###
POST http://localhost:5000/igd/pasien/penanganan/triase/tandavital
Content-Type: application/json 

{
    "id_pasien_igd": 27,
    "tekanan_darah": "Darah manis",
    "frekuensi_nadi": "Darah manis",
    "frekuensi_nafas": "Darah manis",
    "suhu": "Darah manis",
    "sat_o2": "Darah manis",
    "riwayat_alergi_makanan": "Darah manis",
    "riwayat_alergi_obat": "Darah manis",
    "riwayat_alergi_lainya": "Darah manis",
    "berat_badan": "Darah manis",
    "tinggi_badan": "Darah manis"

}

# update triase tanda vital pasien igd
###
PATCH  http://localhost:5000/igd/pasien/penanganan/triase/tandavital/1
Content-Type: application/json

{
    "id_pasien_igd": 27,
    "tekanan_darah": "lknalkjnsdlkjn",
    "frekuensi_nadi": "Darah lknalkjnsdlkjn",
    "frekuensi_nafas": "Darah lknalkjnsdlkjn",
    "suhu": "Darah lknalkjnsdlkjn",
    "sat_o2": "Darah lknalkjnsdlkjn",
    "riwayat_alergi_makanan": "Darah lknalkjnsdlkjn",
    "riwayat_alergi_obat": "Darah lknalkjnsdlkjn",
    "riwayat_alergi_lainya": "Darah lknalkjnsdlkjn",
    "berat_badan": "Darah lknalkjnsdlkjn",
    "tinggi_badan": "Darah lknalkjnsdlkjn"

}

# tampilkan triase anamnesa pasien igd 
###
GET http://localhost:5000/igd/pasien/penanganan/triase/anamnesa/27

# add triase anamnesa pasien igd 
###
POST http://localhost:5000/igd/pasien/penanganan/triase/anamnesa/
Content-Type: application/json 

{
    "id_pasien_igd": 27,
    "keluhan_utama": "Darah manis",
    "riwayat_perjalanan_penyakit": "Darah manis",
    "riwayat_penyakit_terdahulu": "Darah manis",
    "riwayat_pemakaian_obat": "Darah manis",
    "riwayat_penyakit_keluarga": "Darah manis"

}

# update triase anamnesa pasien igd
###
PATCH  http://localhost:5000/igd/pasien/penanganan/triase/anamnesa/1
Content-Type: application/json

{
    "id_pasien_igd": 27,
    "keluhan_utama": "a manis",
    "riwayat_perjalanan_penyakit": "Darah b",
    "riwayat_penyakit_terdahulu": "c manis",
    "riwayat_pemakaian_obat": "Darah d",
    "riwayat_penyakit_keluarga": "f manis"

}


# tampilkan triase pemeriksaan fisik pasien igd 
###
GET http://localhost:5000/igd/pasien/penanganan/triase/pemeriksaanfisik/30

# add triase pemeriksaan fisik pasien igd 
###
POST http://localhost:5000/igd/pasien/penanganan/triase/pemeriksaanfisik/
Content-Type: application/json 

{
    "id_pasien_igd": 30,
    "mata":"mata",
    "telinga":"telinga",
    "hidung":"hidung",
    "mulut":"mulut",
    "tenggorokan":"tenggorokan",
    "leher":"leher",
    "paru":"paru",
    "jantung":"jantung",
    "abdomen":"abdomen",
    "kandungan":"kandungan",
    "kemaluan":"kemaluan",
    "exstremitas":"exstremitas",
    "status_lokalis":"status_lokalis",
    "pemeriksaan_gigi":"pemeriksaan_gigi"

}

# update triase pemeriksaan fisik pasien igd
###
PATCH  http://localhost:5000/igd/pasien/penanganan/triase/pemeriksaanfisik/1
Content-Type: application/json

{
    "id_pasien_igd": 30,
    "mata":"mata kan",
    "telinga":"telinga kan",
    "hidung":"hidung kan",
    "mulut":"mulut kan",
    "tenggorokan":"tenggorokan kan",
    "leher":"lehe kanr",
    "paru":"paru kan",
    "jantung":"jantung kan",
    "abdomen":"abdomen kan",
    "kandungan":"kandungan kan",
    "kemaluan":"kemaluan kan",
    "exstremitas":"exstremita kans",
    "status_lokalis":"status_lokal kanis",
    "pemeriksaan_gigi":"pemeriksaan_gig kani"

}



# tampilkan triase pemeriksaan penunjang pasien igd 
###
GET http://localhost:5000/igd/pasien/penanganan/triase/pemeriksaanpenunjang/30

# add triase pemeriksaan penunjang pasien igd 
###
POST http://localhost:5000/igd/pasien/penanganan/triase/pemeriksaanpenunjang/
Content-Type: application/json 

{
    "id_pasien_igd": 30,
    "jenis_pemeriksaan":"Laboratorium",
    "diagnosa_sementara":"telinga",
    "diagnosa_tambahan":"mata"

}

# update triase pemeriksaan penunjang pasien igd
###
PATCH  http://localhost:5000/igd/pasien/penanganan/triase/pemeriksaanpenunjang/13
Content-Type: application/json

{
    "id_pasien_igd": 30,
    "jenis_pemeriksaan":"Laboratorium",
    "diagnosa_sementara":"teaaalinga",
    "diagnosa_tambahan":"mataaaaa"


}


# tampilkan ATS pasien pada igd triase
###
GET http://localhost:5000/igd/pasien/penanganan/triase/ats/30


# add triase ATS pasien igd 
###
POST http://localhost:5000/igd/pasien/penanganan/triase/ats/
Content-Type: application/json 

{
    "id_pasien_igd": 30,
    "jalan_nafas":"Laboratorium",
    "pernafasan_dewasa":"telinga",
    "pernafasan_anak":"mata"

}

# update triase ATS pasien igd
###
PATCH  http://localhost:5000/igd/pasien/penanganan/triase/ats/91
Content-Type: application/json

{
    "id_pasien_igd": 30,
    "jalan_nafas":"Laboratorium",
    "pernafasan_dewasa":"telinga",
    "pernafasan_anak":"mata"


}

# tampilkan planning dan permasalahan pasien pada igd triase
###
GET http://localhost:5000/igd/pasien/penanganan/triase/permasalahan/30

# add planning dan permasalahan pasien pada igd triase
###
POST http://localhost:5000/igd/pasien/penanganan/triase/permasalahan/
Content-Type: application/json 

{
    "id_pasien_igd": 30,
    "permasalahan_yang_dikonsulkan":"Laboratorium"


}

# update planning dan permasalahan pasien pada igd triase
###
PATCH  http://localhost:5000/igd/pasien/penanganan/triase/permasalahan/1
Content-Type: application/json

{
    "id_pasien_igd": 30,
    "permasalahan_yang_dikonsulkan":"Laboratorium tambah update"


}


# tampilkan kondisi terakhir pasien igd triase
###
GET http://localhost:5000/igd/pasien/penanganan/triase/kondisiterakhir/30

# add kondisi terakhir pasien igd triase
###
POST http://localhost:5000/igd/pasien/penanganan/triase/kondisiterakhir/
Content-Type: application/json 

{

    "id_pasien_igd": 30,
    "keadaan_umum":"Laboratorium",
    "kesadaran":"Laboratorium",
    "tekanan_darah":"Laboratorium",
    "frekuensi_nadi":"Laboratorium",
    "frekuensi_nafas":"Laboratorium",
    "temperature":"Laboratorium",
    "dokter_penanggung_jawab":"Laboratorium"



}

# update kondisi terakhir pasien igd triase
###
PATCH  http://localhost:5000/igd/pasien/penanganan/triase/kondisiterakhir/1
Content-Type: application/json

{
    "id_pasien_igd": 30,
    "keadaan_umum":"Laboratorium c",
    "kesadaran":"Laboratorium v",
    "tekanan_darah":"Laboratorium d",
    "frekuensi_nadi":"Laboratorium v",
    "frekuensi_nafas":"Laboratorium r",
    "temperature":"Laboratorium w",
    "dokter_penanggung_jawab":"Laboratorium l"


}


# asesmen awal pasien igd

###
GET http://localhost:5000/igd/pasien/penanganan/asesmenawal/33

# add kondisi terakhir pasien igd triase
###
POST http://localhost:5000/igd/pasien/penanganan/asesmenawal/
Content-Type: application/json 

{
    "id_pasien_igd":33,
    "kegawatan_pernafasan": "30"

}

# update kondisi terakhir pasien igd triase
###
PATCH  http://localhost:5000/igd/pasien/penanganan/asesmenawal/2
Content-Type: application/json

{
    "id_pasien_igd":33,
    "kegawatan_pernafasan": "berganti"


}


###
GET http://localhost:5000/form/default/igd

# update kondisi terakhir pasien igd triase
###
PATCH  http://localhost:5000/form/default/igd
Content-Type: application/json

{
    "nama_form":"triase"

}
