###
GET http://localhost:5000/users/all?jabatan=perawat&status=tidak aktif

###
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWVVc2VyIjoicm9qYXVyIiwiZW1haWxVc2VyIjoicm9qYXVycmFmaXFpMjVAZ21haWwuY29tIiwiaWF0IjoxNjg3NTE1OTM4LCJleHAiOjE2ODc1MTU5NTN9.OY3Ao26B5-F1CMLE_urFNh15yZIr0YAbLG5aYXbbwbs

###
GET http://localhost:5000/token

###
GET http://localhost:5000/users/4

###
GET http://localhost:5000/users/jabatan

###
PATCH  http://localhost:5000/logout/2

###
POST http://localhost:5000/users/
Content-Type: application/json
{
    "name": "rojaur",
    "email": "rojaurrafiqi25@gmail.com",
    "password": "12345678",
    "confPassword": "12345678",
    "jabatan":"1",
    "jenis_kelamin":"laki-laki",
    "status":"aktif"
}






###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "rojaurrafiqi25@gmail.com",
    "password": "12345678"

}
